#ifndef __UNIT_SLOT_DEFINES_H__
#define __UNIT_SLOT_DEFINES_H__

#include "common/Common.h"

enum EquipmentSlots
{
	EQUIPMENT_SLOT_START				= 0,
	EQUIPMENT_SLOT_HAT					= EQUIPMENT_SLOT_START,
	EQUIPMENT_SLOT_JACKET,
	EQUIPMENT_SLOT_GLOVES,
	EQUIPMENT_SLOT_SNOWBALL_MAKER,
	EQUIPMENT_SLOT_SHOES,
	EQUIPMENT_SLOT_END,
};

#define INVENTORY_CUSTOM_SLOTS_COUNT	3

enum InventorySlots
{
	INVENTORY_SLOT_START				= EQUIPMENT_SLOT_END,
	INVENTORY_SLOT_CUSTOM_START			= INVENTORY_SLOT_START,
	INVENTORY_SLOT_CUSTOM_END			= INVENTORY_SLOT_CUSTOM_START + INVENTORY_CUSTOM_SLOTS_COUNT,
	INVENTORY_SLOT_FIRST_AID			= INVENTORY_SLOT_CUSTOM_END,
	INVENTORY_SLOT_END,
};

#define EQUIPMENT_SLOTS_COUNT			(EQUIPMENT_SLOT_END - EQUIPMENT_SLOT_START)
#define INVENTORY_SLOTS_COUNT			(INVENTORY_SLOT_END - INVENTORY_SLOT_START)
#define UNIT_SLOTS_COUNT				INVENTORY_SLOT_END

#define SLOT_INVALID					-1

inline int32 getInventoryPos(int32 slot) 
{ 
	if(slot >= INVENTORY_SLOT_START && slot < INVENTORY_SLOT_END)
		return slot - INVENTORY_SLOT_START; 
	return SLOT_INVALID;
}

inline int32 getEquipmentPos(int32 slot)
{ 
	if (slot >= EQUIPMENT_SLOT_START && slot < EQUIPMENT_SLOT_END)
		return slot - EQUIPMENT_SLOT_START; 
	return SLOT_INVALID;
}

#endif // __UNIT_SLOT_DEFINES_H__