// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentData.proto

#ifndef PROTOBUF_PaymentData_2eproto__INCLUDED
#define PROTOBUF_PaymentData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include "Transaction.pb.h"
// @@protoc_insertion_point(includes)
class PaymentData;
class PaymentDataDefaultTypeInternal;
extern PaymentDataDefaultTypeInternal _PaymentData_default_instance_;

namespace protobuf_PaymentData_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_PaymentData_2eproto

// ===================================================================

class PaymentData : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:PaymentData) */ {
 public:
  PaymentData();
  virtual ~PaymentData();

  PaymentData(const PaymentData& from);

  inline PaymentData& operator=(const PaymentData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  PaymentData(PaymentData&& from) noexcept
    : PaymentData() {
    *this = ::std::move(from);
  }

  inline PaymentData& operator=(PaymentData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const PaymentData& default_instance();

  static inline const PaymentData* internal_default_instance() {
    return reinterpret_cast<const PaymentData*>(
               &_PaymentData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(PaymentData* other);
  friend void swap(PaymentData& a, PaymentData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline PaymentData* New() const PROTOBUF_FINAL { return New(NULL); }

  PaymentData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from)
    PROTOBUF_FINAL;
  void CopyFrom(const PaymentData& from);
  void MergeFrom(const PaymentData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  void DiscardUnknownFields();
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PaymentData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::std::string GetTypeName() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Transaction transactions = 2;
  int transactions_size() const;
  void clear_transactions();
  static const int kTransactionsFieldNumber = 2;
  const ::Transaction& transactions(int index) const;
  ::Transaction* mutable_transactions(int index);
  ::Transaction* add_transactions();
  ::google::protobuf::RepeatedPtrField< ::Transaction >*
      mutable_transactions();
  const ::google::protobuf::RepeatedPtrField< ::Transaction >&
      transactions() const;

  // string id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  #if LANG_CXX11
  void set_id(::std::string&& value);
  #endif
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // @@protoc_insertion_point(class_scope:PaymentData)
 private:

  ::google::protobuf::internal::InternalMetadataWithArenaLite _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::Transaction > transactions_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  mutable int _cached_size_;
  friend struct protobuf_PaymentData_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// PaymentData

// string id = 1;
inline void PaymentData::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& PaymentData::id() const {
  // @@protoc_insertion_point(field_get:PaymentData.id)
  return id_.GetNoArena();
}
inline void PaymentData::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PaymentData.id)
}
#if LANG_CXX11
inline void PaymentData::set_id(::std::string&& value) {
  
  id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PaymentData.id)
}
#endif
inline void PaymentData::set_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PaymentData.id)
}
inline void PaymentData::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PaymentData.id)
}
inline ::std::string* PaymentData::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:PaymentData.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PaymentData::release_id() {
  // @@protoc_insertion_point(field_release:PaymentData.id)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PaymentData::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:PaymentData.id)
}

// repeated .Transaction transactions = 2;
inline int PaymentData::transactions_size() const {
  return transactions_.size();
}
inline void PaymentData::clear_transactions() {
  transactions_.Clear();
}
inline const ::Transaction& PaymentData::transactions(int index) const {
  // @@protoc_insertion_point(field_get:PaymentData.transactions)
  return transactions_.Get(index);
}
inline ::Transaction* PaymentData::mutable_transactions(int index) {
  // @@protoc_insertion_point(field_mutable:PaymentData.transactions)
  return transactions_.Mutable(index);
}
inline ::Transaction* PaymentData::add_transactions() {
  // @@protoc_insertion_point(field_add:PaymentData.transactions)
  return transactions_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Transaction >*
PaymentData::mutable_transactions() {
  // @@protoc_insertion_point(field_mutable_list:PaymentData.transactions)
  return &transactions_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Transaction >&
PaymentData::transactions() const {
  // @@protoc_insertion_point(field_list:PaymentData.transactions)
  return transactions_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_PaymentData_2eproto__INCLUDED
