#include "WorldOpcodeHandler.h"

#include "game/client/WorldSession.h"

NS_BEGIN


namespace world
{
	char const* gOpcodeNameTable[NUM_MSG_TYPES] = {
		"MSG_NULL",
		"SMSG_AUTH_CHALLENGE",
		"CMSG_AUTH_PROOF",
		"SMSG_AUTH_VERDICT",
		"CMSG_PLAYER_LOGIN",
		"CMSG_PLAYER_LOGOUT",
		"SMSG_THEATER_INFO",
		"CMSG_JOIN_THEATER",
		"SMSG_WAIT_FOR_PLAYERS",
		"SMSG_UPDATE_OBJECT",
		"SMSG_DESTROY_OBJECT",
		"CMSG_QUERY_CHARACTER_INFO",
		"SMSG_CHARACTER_INFO",
		"MSG_MOVE_START",
		"MSG_MOVE_SYNC",
		"MSG_MOVE_HEARTBEAT",
		"MSG_MOVE_TURN",
		"MSG_MOVE_STOP",
		"MSG_ATTACK",
		"SMSG_LAUNCH_RESULT",
		"MSG_CHARGE_START",
		"MSG_CHARGE_STOP",
		"MSG_STAMINA_SYNC",
		"SMSG_MODIFY_STAMINA",
		"SMSG_DEATH_MESSAGE",
		"SMSG_TIME_SYNC_REQ",
		"CMSG_TIME_SYNC_RESP",
		"MSG_PING",
		"MSG_PONG",
		"CMSG_QUERY_WORLD_STATUS",
		"SMSG_WORLD_STATUS",
		"CMSG_QUERY_THEATER_STATUS_LIST",
		"SMSG_THEATER_STATUS_LIST",
		"CMSG_SMILEY_CHAT",
		"CMSG_QUERY_PLAYER_STATUS_LIST",
		"SMSG_PLAYER_STATUS_LIST",
		"CMSG_GM_COMMAND",
		"SMSG_TRANSPORT",
		"SMSG_FLASH_MESSAGE",
		"SMSG_PLAYER_ACTION_MESSAGE",
		"SMSG_REWARD_MESSAGE",
		"SMSG_BATTLE_UPDATE",
		"SMSG_BATTLE_RESULT",
		"SMSG_RELOCATE_LOCATOR",
		"SMSG_ITEM_PICKUP_RESULT",
		"CMSG_USE_ITEM",
		"SMSG_ITEM_USE_RESULT",
		"SMSG_ITEM_APPLICATION_UPDATE",
		"SMSG_ITEM_APPLICATION_UPDATE_ALL",
		"SMSG_ITEM_COOLDOWN_LIST",
		"SMSG_ITEM_ACTION_MESSAGE",
	};

	std::unordered_map<uint16, OpcodeHandler> gOpcodeHandlerTable = {
		{ SMSG_AUTH_CHALLENGE,					{ &WorldSession::handleAuthChallenge				} },
		{ SMSG_AUTH_VERDICT,					{ &WorldSession::handleAuthVerdict					} },
		{ SMSG_THEATER_INFO,					{ &WorldSession::handleTheaterInfo					} },
		{ SMSG_WAIT_FOR_PLAYERS,				{ &WorldSession::handleWaitForPlayers				} },
		{ SMSG_UPDATE_OBJECT,					{ &WorldSession::handleUpdateObject					} },
		{ SMSG_DESTROY_OBJECT,					{ &WorldSession::handleDestroyObject				} },
		{ SMSG_CHARACTER_INFO,					{ &WorldSession::handleCharacterInfo				} },
		{ MSG_MOVE_START,						{ &WorldSession::handleMovementInfo					} },
		{ MSG_MOVE_SYNC,						{ &WorldSession::handleMovementInfo					} },
		{ MSG_MOVE_HEARTBEAT,					{ &WorldSession::handleMovementInfo					} },
		{ MSG_MOVE_TURN,						{ &WorldSession::handleMovementInfo					} },
		{ MSG_MOVE_STOP,						{ &WorldSession::handleMovementInfo					} },
		{ SMSG_LAUNCH_RESULT,					{ &WorldSession::handleLaunchResult					} },
		{ MSG_CHARGE_START,						{ &WorldSession::handleStaminaInfo					} },
		{ MSG_CHARGE_STOP,						{ &WorldSession::handleStaminaInfo					} },
		{ MSG_STAMINA_SYNC,						{ &WorldSession::handleStaminaInfo					} },
		{ SMSG_MODIFY_STAMINA,					{ &WorldSession::handleModifyStamina				} },
		{ SMSG_DEATH_MESSAGE,					{ &WorldSession::handleDeathMessage					} },
		{ SMSG_WORLD_STATUS,					{ &WorldSession::handleWorldStatus					} },
		{ SMSG_THEATER_STATUS_LIST,				{ &WorldSession::handleTheaterStatusList			} },
		{ SMSG_PLAYER_STATUS_LIST,				{ &WorldSession::handlePlayerStatusList				} },
		{ SMSG_TRANSPORT,						{ &WorldSession::handleTransport					} },
		{ SMSG_FLASH_MESSAGE,					{ &WorldSession::handleFlashMessage					} },
		{ SMSG_PLAYER_ACTION_MESSAGE,			{ &WorldSession::handlePlayerActionMessage			} },
		{ SMSG_REWARD_MESSAGE,					{ &WorldSession::handleRewardMessage				} },
		{ SMSG_BATTLE_UPDATE,					{ &WorldSession::handleBattleUpdate					} },
		{ SMSG_BATTLE_RESULT,					{ &WorldSession::handleBattleResult					} },
		{ SMSG_RELOCATE_LOCATOR,				{ &WorldSession::handleRelocateLocator				} },
		{ SMSG_ITEM_PICKUP_RESULT,				{ &WorldSession::handleItemPickupResult				} },
		{ SMSG_ITEM_USE_RESULT,					{ &WorldSession::handleItemUseResult				} },
		{ SMSG_ITEM_APPLICATION_UPDATE,			{ &WorldSession::handleItemApplicationUpdate		} },
		{ SMSG_ITEM_APPLICATION_UPDATE_ALL,		{ &WorldSession::handleItemApplicationUpdateAll		} },
		{ SMSG_ITEM_COOLDOWN_LIST,				{ &WorldSession::handleItemCooldownList				} },
		{ SMSG_ITEM_ACTION_MESSAGE,				{ &WorldSession::handleItemActionMessage			} },
	};
}


NS_END