#ifndef __UPDATE_FIELDS_H__
#define __UPDATE_FIELDS_H__

#include "game/entities/UnitSlotDefines.h"

//
// Server-side data update fields.
// 

enum SUnitField
{
	SUNIT_FIELD_HEALTH					= 0,	// UpdateType: VALUES|CREATE
	SUNIT_FIELD_MAX_HEALTH,						// UpdateType: VALUES|CREATE
	SUNIT_FIELD_MOVEMENT_INFO,					// UpdateType: CREATE
	SUNIT_FIELD_STAMINA_INFO,					// UpdateType: CREATE
	SUNIT_FIELD_MOVE_SPEED,						// UpdateType: VALUES|CREATE
	SUNIT_FIELD_ATTACK_RANGE,					// UpdateType: VALUES|CREATE
	SUNIT_FIELD_ATTACK_TAKES_STAMINA,			// UpdateType: CREATE
	SUNIT_FIELD_DISPLAYID,						// UpdateType: CREATE
	SUNIT_FIELD_LEVEL,							// UpdateType: VALUES|CREATE
	SUNIT_FIELD_SMILEY,							// UpdateType: VALUES|CREATE
	SUNIT_FIELD_UNIT_FLAGS,						// UpdateType: VALUES|CREATE
	SUNIT_FIELD_MAGIC_BEAN_COUNT,				// UpdateType: VALUES|CREATE
	SUNIT_END,
};

enum SPlayerField
{
	SPLAYER_FIELD_IS_GM					= SUNIT_END,		// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_KILL_COUNT,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_EXPERIENCE,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_NEXTLEVEL_XP,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_MONEY,									// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_ITEM_HEAD,								// UpdateType: VALUES|CREATE
	SPLAYER_FIELD_ITEM_END				= SPLAYER_FIELD_ITEM_HEAD + UNIT_SLOTS_COUNT,
	SPLAYER_FIELD_CONCEALMENT_STATE		= SPLAYER_FIELD_ITEM_END,		// UpdateType: VALUES|CREATE 
	SPLAYER_FIELD_PICKUP_DURATION,							// UpdateType: CREATE
	SPLAYER_FIELD_PICKUP_TARGET,							// UpdateType: VALUES|CREATE
	SPLAYER_END,
};

enum SRobotField
{
	SROBOT_FIELD_TARGET					= SUNIT_END,	// UpdateType: VALUES|CREATE
	SROBOT_FIELD_AIACTION_TYPE,							// UpdateType: VALUES|CREATE
	SROBOT_FIELD_AIACTION_STATE,						// UpdateType: VALUES|CREATE
	SROBOT_END,
};

enum SItemBoxField
{
	SITEMBOX_FIELD_POSITION				= 0,	// UpdateType: CREATE
	SITEMBOX_FIELD_DIRECTION,					// UpdateType: CREATE
	SITEMBOX_FIELD_HEALTH,						// UpdateType: VALUES|CREATE
	SITEMBOX_FIELD_MAX_HEALTH,					// UpdateType: VALUES|CREATE
	SITEMBOX_END,
};

enum SItemField
{
	SITEM_FIELD_ITEMID					= 0,	// UpdateType: CREATE
    SITEM_FIELD_POSITION,						// UpdateType: CREATE
	SITEM_FIELD_COUNT,							// UpdateType: CREATE
	SITEM_FIELD_HOLDER,							// UpdateType: CREATE
	SITEM_FIELD_HOLDER_ORIGIN,					// UpdateType: CREATE
	SITEM_FIELD_LAUNCH_CENTER,					// UpdateType: CREATE
	SITEM_FIELD_LAUNCH_RADIUS_IN_MAP,			// UpdateType: CREATE
	SITEM_FIELD_DROP_DURATION,					// UpdateType: CREATE
	SITEM_FIELD_DROP_ELAPSED,					// UpdateType: CREATE
    SITEM_END, 
};

enum SProjectileField
{
	SPROJECTILE_FIELD_LAUNCHER			= 0,	// UpdateType: CREATE
	SPROJECTILE_FIELD_LAUNCHER_ORIGIN,			// UpdateType: CREATE
	SPROJECTILE_FIELD_ATTACK_RANGE,				// UpdateType: CREATE
	SPROJECTILE_FIELD_LAUNCH_CENTER,			// UpdateType: CREATE
	SPROJECTILE_FIELD_LAUNCH_RADIUS_IN_MAP,		// UpdateType: CREATE
	SPROJECTILE_FIELD_ORIENTATION,				// UpdateType: CREATE
	SPROJECTILE_FIELD_ELAPSED,					// UpdateType: CREATE
	SPROJECTILE_FIELD_DURATION,					// UpdateType: CREATE
	SPROJECTILE_FIELD_ATTACK_COUNTER, 			// UpdateType: CREATE
	SPROJECTILE_FIELD_CONSUMED_STAMINA,			// UpdateType: CREATE
	SPROJECTILE_FIELD_SCALE,					// UpdateType: CREATE
	SPROJECTILE_FIELD_ATTACK_INFO_COUNTER,		// UpdateType: CREATE
	SPROJECTILE_FIELD_STATUS,						// UpdateType: CREATE
	SPROJECTILE_END,
};

enum SLocatorUnitField
{
	SUNIT_LOCATOR_FIELD_LOCATION		= 0,	// UpdateType: CREATE
	SUNIT_LOCATOR_FIELD_DISPLAYID,				// UpdateType: CREATE
	SUNIT_LOCATOR_FIELD_IS_ALIVE,				// UpdateType: VALUES|CREATE
	SUNIT_LOCATOR_FIELD_MOVE_SPEED,				// UpdateType: VALUES|CREATE
	SUNIT_LOCATOR_END,
};

enum SCarriedItemField
{
	SCARRIEDITEM_FIELD_ITEMID			= 0,	// UpdateType: CREATE
	SCARRIEDITEM_FIELD_LEVEL,					// UpdateType: CREATE
	SCARRIEDITEM_FIELD_COUNT,					// UpdateType: VALUES|CREATE
	SCARRIEDITEM_FIELD_STACKABLE,				// UpdateType: CREATE
	SCARRIEDITEM_FIELD_COOLDOWN_DURATION,		// UpdateType: CREATE
	SCARRIEDITEM_END,
};

//
// Client-side data update fields.
// 

enum CUnitField
{
	CUNIT_FIELD_NAME					= 0,
	CUNIT_FIELD_HEALTH,
	CUNIT_FIELD_MAX_HEALTH,
	CUNIT_FIELD_MOVE_SPEED,
	CUNIT_FIELD_ATTACK_RANGE,
	CUNIT_FIELD_POSITION,
	CUNIT_FIELD_MOVEMENT_FLAG,
	CUNIT_FIELD_DIRECTION,
	CUNIT_FIELD_IS_ALIVE,
	CUNIT_FIELD_LEVEL,
	CUNIT_FIELD_SMILEY,
	CUNIT_FIELD_STAMINA,
	CUNIT_FIELD_PROJECTILE_SCALE,
	CUNIT_FIELD_MAGIC_BEAN_COUNT,
	CUNIT_END,
};

enum CPlayerField
{
	CPLAYER_FIELD_IS_GM					= CUNIT_END,
	CPLAYER_FIELD_KILL_COUNT,
	CPLAYER_FIELD_MAX_STAMINA,
	CPLAYER_FIELD_STAMINA_REGEN_RATE,
	CPLAYER_FIELD_EXPERIENCE,
	CPLAYER_FIELD_NEXTLEVEL_XP,
	CPLAYER_FIELD_MONEY,
	CPLAYER_FIELD_ITEM_HEAD,
	CPLAYER_FIELD_ITEM_END				= CPLAYER_FIELD_ITEM_HEAD + UNIT_SLOTS_COUNT,
	CPLAYER_FIELD_CONCEALMENT_STATE		= CPLAYER_FIELD_ITEM_END,
	CPLAYER_FIELD_PICKUP_TARGET,
	CPLAYER_END,
};

enum CRobotField
{
	CROBOT_FIELD_TARGET					= CUNIT_END,
	CROBOT_FIELD_AIACTION_TYPE,
	CROBOT_FIELD_AIACTION_STATE,
	CROBOT_END,
};

enum CItemBoxField
{
	CITEMBOX_FIELD_HEALTH,
	CITEMBOX_FIELD_MAX_HEALTH,
	CITEMBOX_FIELD_IS_LOCKED,
	CITEMBOX_END
};

enum CItemField
{
	CITEM_FIELD_IS_AVAILABLE,
    CITEM_END
};

enum CProjectileField
{
	CPROJECTILE_END
};

enum CLocatorUnitField
{
	CUNIT_LOCATOR_FIELD_IS_ALIVE,
	CUNIT_LOCATOR_END,
};

enum CCarriedItemField
{
	CCARRIEDITEM_FIELD_COUNT,
	CCARRIEDITEM_END,
};

#endif // __UPDATE_FIELDS_H__
